import unittest
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]


class MapPinStyleContracts(unittest.TestCase):
    def test_vehicle_pin_uses_group_insurance_status_as_ring(self):
        html = (ROOT_DIR / "web" / "partials" / "app_shell.html").read_text(encoding="utf-8")
        css = (ROOT_DIR / "web" / "styles" / "map_pins.css").read_text(encoding="utf-8")
        layer_css = (ROOT_DIR / "web" / "styles" / "map_layers.css").read_text(encoding="utf-8")
        tokens_css = (ROOT_DIR / "web" / "styles" / "tokens.css").read_text(encoding="utf-8")
        config_js = (ROOT_DIR / "web" / "config.js").read_text(encoding="utf-8")
        markers_js = (ROOT_DIR / "web" / "app" / "map_markers.js").read_text(encoding="utf-8")
        vehicle_layer_js = (ROOT_DIR / "web" / "app" / "vehicle_layer.js").read_text(encoding="utf-8")
        vehicle_resolution_js = (ROOT_DIR / "web" / "app" / "vehicle_resolution.js").read_text(encoding="utf-8")
        i18n_js = "\n".join(
            (ROOT_DIR / "web" / path).read_text(encoding="utf-8") for path in ("i18n/pl.js", "i18n/en.js")
        )

        self.assertIn("function vehicleIcon(", markers_js)
        self.assertIn("insuranceStatus = FIELD_PHOTO_VEHICLE_INSURANCE_STATUS_UNKNOWN", markers_js)
        self.assertIn("isLongStanding = false", markers_js)
        self.assertIn("FIELD_PHOTO_VEHICLE_INSURANCE_STATUSES.has(insuranceStatus)", markers_js)
        self.assertIn("vehicle-pin--insurance-${safeInsuranceStatus}", markers_js)
        self.assertIn("const VEHICLE_LONG_STANDING_DEFAULT_DAYS = 30;", config_js)
        self.assertIn("const VEHICLE_LONG_STANDING_DAY_OPTIONS = [30, 60, 90];", config_js)
        self.assertIn("VEHICLE_STANDING_FILTER_DAYS_STORAGE_KEY", config_js)
        self.assertIn("VEHICLE_RESOLUTION_FILTER_STORAGE_KEY", config_js)
        self.assertIn("FIELD_PHOTO_VEHICLE_RESOLUTION_STATUS_ACTIVE", config_js)
        self.assertIn("FIELD_PHOTO_VEHICLE_RESOLUTION_STATUS_REMOVED", config_js)
        self.assertIn("vehicle-pin--long-standing", markers_js + css)
        self.assertIn("vehicle-pin--removed", markers_js + css)
        self.assertIn("function vehicleGroupIsLongStanding", vehicle_layer_js)
        self.assertIn("function vehicleGroupResolutionStatus", vehicle_resolution_js)
        self.assertIn("function vehicleGroupMatchesResolutionFilter", vehicle_resolution_js)
        self.assertIn("fieldPhotoGroupStartTimestamp(group.photos, nowMs)", vehicle_layer_js)
        self.assertIn("function vehicleLongStandingMs", vehicle_layer_js)
        self.assertNotIn("VEHICLE_LONG_STANDING_MS", config_js + vehicle_layer_js)
        self.assertIn(
            "vehicleGroupIsLongStanding(group)",
            vehicle_layer_js,
        )
        self.assertIn("const VEHICLE_FILTER_ALL = 'all';", vehicle_layer_js)
        self.assertIn("const VEHICLE_INSURANCE_FILTER_INSURED = 'insured';", vehicle_layer_js)
        self.assertIn("const VEHICLE_STANDING_FILTER_OFF = 0;", vehicle_layer_js)
        self.assertIn("const VEHICLE_MARKER_BASE_Z_INDEX = 1200;", vehicle_layer_js)
        self.assertIn("function vehicleGroupMatchesInsuranceFilter", vehicle_layer_js)
        self.assertIn("function vehicleGroupMatchesStandingFilter", vehicle_layer_js)
        self.assertIn("function vehicleGroupMatchesPhotoFilter", vehicle_layer_js)
        self.assertIn("function vehicleGroupMatchesFilters", vehicle_layer_js)
        self.assertIn("function visibleVehicleGroups", vehicle_layer_js)
        self.assertIn("function vehicleGroupStatusPriority", vehicle_layer_js)
        self.assertIn("function vehicleGroupZIndexOffset", vehicle_layer_js)
        self.assertIn("function prioritizedVehicleGroups", vehicle_layer_js)
        self.assertIn("prioritizedVehicleGroups().forEach", vehicle_layer_js)
        self.assertIn("zIndexOffset: vehicleGroupZIndexOffset(group)", vehicle_layer_js)
        self.assertIn("function setVehicleInsuranceFilter", vehicle_layer_js)
        self.assertIn("function setVehicleStandingFilterDays", vehicle_layer_js)
        self.assertIn("function cycleVehicleInsuranceFilter", vehicle_layer_js)
        self.assertIn("function cycleVehicleStandingFilterDays", vehicle_layer_js)
        self.assertIn("function cycleVehiclePhotoFilterMin", vehicle_layer_js)
        self.assertIn("function cycleVehicleResolutionFilter", vehicle_resolution_js)
        self.assertIn("const VEHICLE_INSURANCE_FILTER_CYCLE", vehicle_layer_js)
        self.assertIn("const VEHICLE_STANDING_FILTER_DAYS_CYCLE", vehicle_layer_js)
        self.assertIn("const VEHICLE_PHOTO_FILTER_MIN_CYCLE", vehicle_layer_js)
        self.assertIn("const VEHICLE_RESOLUTION_FILTER_CYCLE", vehicle_resolution_js)
        self.assertIn("function vehicleFilterCounts", vehicle_layer_js)
        self.assertIn("function updateVehicleFilterControlsAndCounts", vehicle_layer_js)
        self.assertIn("function vehicleMarkerTooltip", vehicle_layer_js)
        self.assertNotIn("title: markerTooltip", vehicle_layer_js)
        self.assertNotIn("title: markerTitle", vehicle_layer_js)
        self.assertIn("alt: markerTooltip", vehicle_layer_js)
        self.assertIn("marker.getElement()?.setAttribute('aria-label', markerTooltip)", vehicle_layer_js)
        self.assertIn("marker.bindTooltip(markerTooltip", vehicle_layer_js)
        self.assertIn("popupElapsedAgeText(group.photos)", vehicle_layer_js)
        self.assertIn("vehicle.markerTooltipPhotos", i18n_js)
        self.assertIn("vehicle.markerTooltipAge", i18n_js)
        self.assertIn("vehicle.markerTooltipInsurance", i18n_js)
        self.assertIn("vehicle.markerTooltipRemoved", i18n_js)
        self.assertIn("vehicle.markerInsuranceShort.insured", i18n_js)
        self.assertIn(
            "visibleVehicleGroups().length", (ROOT_DIR / "web" / "app" / "field_photos.js").read_text(encoding="utf-8")
        )
        self.assertIn(
            "updateVehicleFilterControlsAndCounts()",
            (ROOT_DIR / "web" / "app" / "field_photos.js").read_text(encoding="utf-8"),
        )
        self.assertIn('class="layer-toggle layer-toggle--vehicle"', html)
        self.assertIn('class="vehicle-filter-tray"', html)
        self.assertEqual(html.count('class="vehicle-cycle-filter"'), 4)
        self.assertIn('id="vehicle-insurance-cycle-filter"', html)
        self.assertIn('id="vehicle-standing-cycle-filter"', html)
        self.assertIn('id="vehicle-photo-cycle-filter"', html)
        self.assertIn('id="vehicle-resolution-cycle-filter"', html)
        self.assertIn('onclick="cycleVehicleInsuranceFilter()"', html)
        self.assertIn('onclick="cycleVehicleStandingFilterDays()"', html)
        self.assertIn('onclick="cycleVehiclePhotoFilterMin()"', html)
        self.assertIn('onclick="cycleVehicleResolutionFilter()"', html)
        self.assertIn("vehicle-insurance-filter-count", html)
        self.assertIn("vehicle-standing-filter-count", html)
        self.assertIn("vehicle-photo-filter-count", html)
        self.assertIn("vehicle-resolution-filter-count", html)
        self.assertNotIn('data-vehicle-insurance-filter="insured"', html)
        self.assertNotIn('data-vehicle-standing-filter-days="30"', html)
        self.assertNotIn('class="vehicle-status-filter"', html)
        self.assertNotIn('class="vehicle-age-threshold"', html)
        self.assertNotIn('class="map-pin-legend"', html)
        self.assertIn("grid-template-columns: repeat(4, minmax(0, 1fr));", layer_css)
        self.assertIn("padding: 0 8px 8px;", layer_css)
        self.assertNotIn("padding: 0 8px 8px 36px;", layer_css)
        self.assertIn(".vehicle-cycle-filter.is-active", layer_css)
        self.assertIn(".vehicle-cycle-filter-label", layer_css)
        self.assertIn(".vehicle-filter-count", layer_css)
        self.assertIn(".vehicle-filter-count.is-empty", layer_css)
        self.assertIn(".vehicle-photo-dot", layer_css)
        self.assertIn(".vehicle-resolution-dot", layer_css)
        self.assertIn(".leaflet-tooltip.vehicle-marker-tooltip", css)
        self.assertIn("layers.vehicleFilterCountLabel", i18n_js)
        self.assertIn("layers.vehicleFilters", html + i18n_js)
        self.assertIn("layers.vehicleInsuranceCycleOff", i18n_js)
        self.assertIn("layers.vehicleInsuranceCycleStatus", i18n_js)
        self.assertIn("layers.vehicleStandingCycleOff", i18n_js)
        self.assertIn("layers.vehicleStandingCycleDays", i18n_js)
        self.assertIn("layers.vehiclePhotoCycleOff", i18n_js)
        self.assertIn("layers.vehiclePhotoCycleMin", i18n_js)
        self.assertIn("layers.vehicleResolutionCycleActive", i18n_js)
        self.assertIn("layers.vehicleResolutionCycleAll", i18n_js)
        self.assertIn("layers.vehicleResolutionCycleRemoved", i18n_js)
        for status in ("unknown", "insured", "uninsured"):
            self.assertIn(f"--pin-insurance-{status}-ring:", tokens_css)
            self.assertIn(f".vehicle-pin--insurance-{status}", css)
        self.assertIn("--pin-vehicle-removed-ring:", tokens_css)
        self.assertIn(".vehicle-pin--removed", css)
        self.assertIn("border: 3px solid var(--pin-vehicle-current-ring);", css)
        self.assertIn("box-shadow: var(--pin-dot-shadow), 0 0 0 2px var(--pin-vehicle-current-ring-soft);", css)
        self.assertIn("map-pin-age-dot", html + layer_css)
        for status in ("unknown", "insured", "uninsured"):
            self.assertIn(f"map-pin-status-ring--{status}", html + layer_css)

    def test_low_zoom_dot_mode_uses_distinct_shapes_for_place_types(self):
        css = (ROOT_DIR / "web" / "styles" / "map_pins.css").read_text(encoding="utf-8")

        self.assertIn(".marker-detail--dots .vehicle-pin {", css)
        self.assertIn("width: 16px;", css)
        self.assertIn("border: 3px solid var(--pin-vehicle-current-ring);", css)
        self.assertIn(".marker-detail--dots .field-photo-pin--infrastructure {", css)
        self.assertIn("transform: translate(10px, 27px) rotate(45deg);", css)
        self.assertIn(".marker-detail--dots .field-photo-pin--smoke {", css)
        self.assertIn("height: 10px;", css)
        self.assertIn("border-radius: var(--radius-full);", css)
        self.assertIn(".marker-detail--dots .pending-submission-pin {", css)
        self.assertIn("border: 2px dashed var(--pin-pending-ring);", css)
        self.assertNotIn("width: 12px;\n    height: 12px;\n    border-radius: 50%;", css)

    def test_pending_vehicle_photos_decorate_existing_vehicle_pin(self):
        css = (ROOT_DIR / "web" / "styles" / "map_pins.css").read_text(encoding="utf-8")
        markers_js = (ROOT_DIR / "web" / "app" / "map_markers.js").read_text(encoding="utf-8")
        field_photos_js = (ROOT_DIR / "web" / "app" / "field_photos.js").read_text(encoding="utf-8")
        vehicle_layer_js = (ROOT_DIR / "web" / "app" / "vehicle_layer.js").read_text(encoding="utf-8")
        vehicle_resolution_js = (ROOT_DIR / "web" / "app" / "vehicle_resolution.js").read_text(encoding="utf-8")
        i18n_js = "\n".join(
            (ROOT_DIR / "web" / path).read_text(encoding="utf-8") for path in ("i18n/pl.js", "i18n/en.js")
        )

        self.assertIn("pendingCount = 0", markers_js)
        self.assertIn("vehicle-pin--mixed-pending", markers_js + css)
        self.assertIn("vehicle-pin-pending-indicator", markers_js + css)
        self.assertIn("function attachPendingVehiclePhotosToGroups", vehicle_layer_js)
        self.assertIn("pendingPhotos.push(photo)", vehicle_layer_js)
        self.assertIn("function pendingVehiclePhotoAttachedToApprovedGroup", field_photos_js)
        self.assertIn("!pendingVehiclePhotoAttachedToApprovedGroup(photo, approvedVehicleGroups)", field_photos_js)
        self.assertIn(
            "const approvedVehicleGroups = vehicleLayerAllowed() ? visibleVehicleGroups(photos) : [];", field_photos_js
        )
        self.assertIn("encodedApprovedPhotoIds", vehicle_layer_js + vehicle_resolution_js)
        self.assertIn("encodedEditablePhotoIds", vehicle_layer_js)
        self.assertIn("vehicle.popup.pendingBadge", i18n_js)
        self.assertIn("vehicle.markerTooltipPendingPhotos", i18n_js)
